use pandash;
drop table assignments;
drop table assignment_attachments;
drop table courses;
drop table instructors;
drop table quizzes;
drop table resources;
drop table students;
drop table studentassignments;
drop table studentcourses;
drop table studentquizzes;
drop table studentresources;
drop table forums;
